[package]
name = "worker-rust"
version = "0.1.0"
edition = "2021"

# https://github.com/rustwasm/wasm-pack/issues/1247
[package.metadata.wasm-pack.profile.release]
wasm-opt = false

[lib]
crate-type = ["cdylib"]

[dependencies]
base64 = "0.21.5"
chrono = "0.4.31"
http = "1.0.0"
lazy_static = "1.4.0"
worker = { git = "https://github.com/fwqaaq/workers-rs", branch = "with-http" }

[profile.release]
lto = true
strip = true
codegen-units = 1
